source 'http://rubygems.org'
gem 'rack', '>= 1.0.0'
gem 'sinatra', '1.3.2', :require => 'sinatra/base'
gem 'rack-reverse-proxy', '0.4.4', :require => 'rack/reverse_proxy', :path => './gems/rack-reverse-proxy'
gem 'thin'
gem 'rack-ssl-enforcer'